[[redirects]]
  from = "https://anmeldung.onlang.de"
  to = "https://anmeldung.onlang.de/anmeldung.html"
  status = 301
  force = true

[[redirects]]
  from = "https://anmeldung.onlang.de/"
  to = "https://anmeldung.onlang.de/anmeldung.html"
  status = 301
  force = true

[[redirects]]
  from = "https://admin.onlang.de"
  to = "https://admin.onlang.de/admin.html"
  status = 301
  force = true

[[redirects]]
  from = "https://admin.onlang.de/"
  to = "https://admin.onlang.de/admin.html"
  status = 301
  force = true

[[redirects]]
  from = "https://dashboard.onlang.de"
  to = "https://dashboard.onlang.de/dashboard.html"
  status = 301
  force = true

[[redirects]]
  from = "https://dashboard.onlang.de/"
  to = "https://dashboard.onlang.de/dashboard.html"
  status = 301
  force = true
